[helpers]

[default]
depends = ["emacs", "git"]

[default.files]

[default.variables]

[emacs.files]	
"emacs/init.el" = "~/.emacs.d/init.el"

[git.files]
"git/.gitconfig" = "~/.gitconfig"

[settings]
default_target_type = "automatic"
