[helpers]

[default]
depends = ["emacs", "git"]

[default.files]

[default.variables]

[termux.files]
"termux/colors.properties" = "~/.termux/colors.properties"
"termux/start-x11" = "~/.shortcuts/start-x11"

[emacs.files]	
"emacs/init.el" = "~/.emacs.d/init.el"

[git.files]
"git/.gitconfig" = "~/.gitconfig"

[starship.files]
"starship/config.toml" = "~/.config/starship/config.toml"

[settings]
default_target_type = "automatic"
